### PR TITLE
fix THUCYDIDES-160 (no candidate steps found when path contains spaces)

### PR DESCRIPTION
**Pull request by cvmocanu**
The expression "new File(url.getFile())" is buggy because the result of
"url.getFile()" contains url-encoded characters (like "%20" instead of
space).
The fix is to use "new File(url.toURI())" instead, since that takes care
of decoding url-encoded characters.

See also: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4466485

### CODE REVIEW

**Comment by wakaleo** [comment]
Actually this breaks the existing soln, did you run the tests on your machine?

**Comment by cvmocanu** [comment]
I have not run the tests, sorry.
I will try to fix them now.

I had an issue with "net.thucydides:thucydides-test-utils:jar:0.9.250" not being found in maven central repo. I built it locally from sources.

**Comment by cvmocanu** [comment]
For fixing the tests, do you want me to create a new commit or amend the existing commit (so that the problem does not exist in the history)?

**Comment by wakaleo** [comment]
You can amend the existing commit - also, make sure you add some tests that
illustrate what you are trying to fix.

On 27 June 2014 17:42, Cristian Vasile Mocanu notifications@github.com
wrote:

> For fixing the tests, do you want me to create a new commit or amend the
> existing commit (so that the problem does not exist in the history)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thucydides-webtests/thucydides-jbehave/pull/7#issuecomment-47316325
> .

## 

---

John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com

---

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming _BDD/TDD Master classes_
http://wakaleo.com/training/testing-and-tdd-for-java-developers and
our _Advanced
BDD Requirements Workshops
http://wakaleo.com/training/advanced-agile-requirements-workshop_, coming
soon to _Sydney
http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses
*
and *Melbourne
http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses!_

---

**Comment by cvmocanu** [comment]
I have 2 questions:

(1)
I checked out the commit before my changes and I have a lot of tests failing or erroring-out (e.g. NullPointerExceptions).
I also built from tag "thucydides-jbehave-plugin-0.9.250" and I have the same problem.

Do I need to run the tests with special system properties (like webdriver properties, path to phantomjs, etc.)? I just did "mvn clean test" from the root of "thucydides-jbehave".

(2) The problem that I am trying to fix is reading classes when the path to them contains spaces (or other characters that gets url-encoded). To be able to test this I need somehow to have a class in the classpath, such that the path contains spaces.
One solution that I can think of is to make the build directory for test resources "target/test classes" instead of "target/test-classes" (replace dash with space). I think this is possible in maven. Do you think that would be a good solution?

**Comment by wakaleo** [comment]
The build is not designed to run when there are spaces on the path (due to the same JDK issue). There are tests with requirements directories containing spaces, but the problem is related to how the resources are read from the classpath.

**Pull request merged**
