### PR TITLE
Thucydides 107

### PR DESCRIPTION
**Pull request by mdolinin**
Hi John,

I try to fix this bug http://java.net/jira/browse/THUCYDIDES-107.

This feature http://jbehave.org/reference/stable/given-stories.html would be very useful, for scenarios where user must be logged before some actions at webapp.

Thanks, 
Michael

### CODE REVIEW

**Comment by wakaleo** [comment]
Nice work, thanks!

**Comment by BrooksFoley** [comment]
I am running into an issue with thucydides and jbehave. With thucydides when I try to run my project I am getting an error that says

javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Cannot open connection
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1235)
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1168)
    at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1245)
    at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:63)
    at net.thucydides.core.statistics.dao.HibernateTestOutcomeHistoryDAO.storeTestOutcomes(HibernateTestOutcomeHistoryDAO.java:166)
    at net.thucydides.core.statistics.StatisticsListener.storePending(StatisticsListener.java:74)
    at net.thucydides.core.statistics.StatisticsListener.testSuiteFinished(StatisticsListener.java:67)
    at net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:401)
    at net.thucydides.jbehave.ThucydidesReporter.afterStory(ThucydidesReporter.java:262)...

and complains about 
Caused by: org.h2.jdbc.JdbcSQLException: Exception opening port "H2 TCP Server (tcp://x.xxx.xxx.211:63880)" (port may be in use), cause: "timeout; please check your network configuration, specially the file /etc/hosts" [90061-160]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
    at org.h2.message.DbException.get(DbException.java:169)
    at org.h2.tools.Server.start(Server.java:376)

I masked off the IP addess above but it is essentially pointing to the machine that I am running on.  
The person I am working with on this in my office is not seeing the same problem and we are using the same project and our ect/host files are the same. I am running with the 9.98 thucydides-jbehave-plugin.
Is this something that you have seen before? Is there some configuration on my machine that is not set?

**Comment by wakaleo** [comment]
Sometimes the H2 database used to store test statistics gets locked if the
JVM exits violently. Have a look in the ".thucydides" directory in your
home directory, and try removing any files ending in "lock.db"
- John.

On 7 March 2013 10:39, BrooksFoley notifications@github.com wrote:

> I am running into an issue with thucydides and jbehave. With thucydides
> when I try to run my project I am getting an error that says
> 
> javax.persistence.PersistenceException:
> org.hibernate.exception.GenericJDBCException: Cannot open connection
> at
> org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1235)
> at
> org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1168)
> at
> org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1245)
> at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:63)
> at
> net.thucydides.core.statistics.dao.HibernateTestOutcomeHistoryDAO.storeTestOutcomes(HibernateTestOutcomeHistoryDAO.java:166)
> at
> net.thucydides.core.statistics.StatisticsListener.storePending(StatisticsListener.java:74)
> at
> net.thucydides.core.statistics.StatisticsListener.testSuiteFinished(StatisticsListener.java:67)
> at
> net.thucydides.core.steps.StepEventBus.testSuiteFinished(StepEventBus.java:401)
> at
> net.thucydides.jbehave.ThucydidesReporter.afterStory(ThucydidesReporter.java:262)...
> 
> and complains about
> Caused by: org.h2.jdbc.JdbcSQLException: Exception opening port "H2 TCP
> Server (tcp://x.xxx.xxx.211:63880)" (port may be in use), cause: "timeout;
> please check your network configuration, specially the file /etc/hosts"
> [90061-160]
> at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
> at org.h2.message.DbException.get(DbException.java:169)
> at org.h2.tools.Server.start(Server.java:376)
> 
> I masked off the IP addess above but it is essentially pointing to the
> machine that I am running on.
> 
> The person I am working with on this in my office is not seeing the same
> problem and we are using the same project and our ect/host files are the
> same. I am running with the 9.98 thucydides-jbehave-plugin.
> Is this something that you have seen before? Is there some configuration
> on my machine that is not set?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thucydides-webtests/thucydides-jbehave/pull/1#issuecomment-14533680
> .

## 

---

John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com

**Comment by BrooksFoley** [comment]
John, Thanks. I removed the stats-default.lock.db file and tried to run it again, but no luck.
The story runs through the GivenStories (its only one story) and then encounters the error. I get the same thing when I don't use GivenStories but it occurs after the last scenario has run. 
Any other thoughts?

-Brooks

**Comment by wakaleo** [comment]
I've seen this happen from time to time, but it's tricky to isolate what is
causing it. Here are some things to try:
- Delete all the files in ~/.thucydides
- Deactivate statistics on your machine using
  -Dthucydides.record.statistics=false

On 7 March 2013 12:42, BrooksFoley notifications@github.com wrote:

> John, Thanks. I removed the stats-default.lock.db file and tried to run it
> again, but no luck.
> The story runs through the GivenStories (its only one story) and then
> encounters the error. I get the same thing when I don't use GivenStories
> but it occurs after the last scenario has run.
> Any other thoughts?
> 
> -Brooks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thucydides-webtests/thucydides-jbehave/pull/1#issuecomment-14538274
> .

## 

---

John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com

**Pull request merged**
